import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { sendMsgToOpenAi } from './openai'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const msgEnd = useRef(null)

  const [input, setInput] = useState("");
  const [messages, setMessages] = useState({
    text: "Hi, I am ChatGPT",
    isBot: true,

  });

  useEffect(() => {
    msgEnd.current.scrollIntoView();
  }, [messages])

  const handleSend = async () => {
    const text = input;
    setInput('');
    setMessages([
      ...messages,
      { text, isBot: false }
    ])
    const res = await sendMsgToOpenAI(input);
    setMessages([
      ...messages,
      { text, isBot: false },
      { text: res, isBot: true }
    ]);
  }

  return (
    <>
      <Head>
        <title>ChatGPT Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.app}>
        <div className={styles.sideBar}>
          <div className={styles.upperSide}>
            <div className={styles.upperSideTop}>
              <img src="./gptlogo.webp" alt="Logo" className={styles.logo} />
              <span className={styles.brand}>ChatGPT</span>
              <button className={styles.midBtn}>
                <img src="./assets/add-30.png" alt="new chat" className={styles.addBtn} />
                New Chat
              </button>
              <div className={styles.upperSideBottom}>
                <button className={styles.query}>
                  <img src="./assets/message.svg" alt="" /> What is Programing ?
                </button>
                <button className={styles.query}>
                  <img src="./assets/message.svg" alt="" /> How to use an API ?
                </button>
              </div>
            </div>
          </div>
          <div className={styles.lowerSide}>
            <div className={styles.listItems}><img src="./assets/home.svg" alt="" className={styles.listItemsImg} />Home</div>
            <div className={styles.listItems}><img src="./assets/bookmark.svg" alt="" className={styles.listItemsImg} />Saved</div>
            <div className={styles.listItems}><img src="./assets/rocket.svg" alt="" className={styles.listItemsImg} />Upgrade to Pro</div>
          </div>
        </div>
        <div className={styles.main}>
          <div className={styles.chats}>
            <div className={styles.chat}>
              <img className={styles.chatImg} src="./assets/user-icon.png" alt="" />
              <p className={styles.txt}>
                lorem ipsuim
              </p>
            </div>
            {messages.map((message, i) => {
              <div key={i} className={message.isBot ? `${styles.chat} ${styles.bot}` : `${styles.chat}`}>
                <img className={styles.chatImg} src={message.isBot ? "./assets/chatgptLogo.svg" : "./assets/user-icon.png"} alt="" />
                <p className={styles.txt}>{message.text}</p>
              </div>
            })}
            <div ref={msgEnd}></div>
          </div>
          <div className={styles.chatFooter}>
            <div className={styles.inp}>
              <input type={styles.text} name="" id="" placeholder='Send a message' value={input} onChange={(e) => { setInput(e.target.value) }} />
              <button className={styles.send} onClick={handleSend}>
                <img src="./assets/send.svg" alt="Send" />
              </button>
            </div>
            <p>ChatGPT may produce inaccurate</p>
          </div>
        </div>
      </div>
    </>
  )
}
